### ISSUE TITLE
Versioning for schema changes

### ISSUE THREAD

**Issue by JohT** [eclipse-ee4j/jsonb-api#192]
**Problem:**
When changing objects, their JSON representation changes too.
Trying to deserialize a newer version of an object with an older JSON representation may fail. In API's, this is known as "breaking changes".
Storing JSON representations in a long term manner (e.g. in an event store for event sourcing) leads to big challenges (see "The Dark Side of Event Sourcing: Managing Data Conversion").

**Example:**
1. `{"name":"John Doe"}`
2. `{"forename":"John","surename":"Doe"}`
3. `{"name":{"forename":"John","surename":"Doe"}}`
4. `{"name":{"forename":"John","surename":"Doe","title":"Dr"}}`

**Some attempts:**
- Google's GSON has build in annotations called [GSON @Until](https://static.javadoc.io/com.google.code.gson/gson/2.6.1/com/google/gson/annotations/Until.html) and [GSON @Since](https://static.javadoc.io/com.google.code.gson/gson/2.6.1/com/google/gson/annotations/Since.html)
- [pengyuc/jackson-versioning](https://github.com/pengyuc/jackson-versioning)
- [jonpeterson/jackson-module-model-versioning](https://github.com/jonpeterson/jackson-module-model-versioning)

**My thoughts:**
Maybe this could be addressed by providing a method per version inside the value object, that is able to convert the previous version to the current one. The previous versions of the value object may be renamed to ...V1, ...V2 and put inside the main value object as static inner classes. Methods (instead of annotations only) have the advantage to contain flexible and more complex ways to "upcast" the Version. 

The value object may need an "version" field. It would be hard to detect the version of an serialized JSON. But even that could also be done using a method.

This methods could be annotated. Maybe they could also be configured, so that the value objects does not need to get cluttered with annotations. But thats just a thought.

**Comment by rmannibucau** [comment]
Hi,

Johnzon has that as well and you set the version on the jsonb instance - because an object cant hold it alone due to the graph management.

Now, with serializers it becomes no pore needed since serializers are a trivial way to handle it the way you want.

In other words, if you want to do it generically, you must set up an annotation, a config (on jsonbconfig), potentially an enrichment mode gor the version value (wrapped, inline, ...), and some activation condition (how to compare versions for example). You must also define the behavior (fail, fallback mapping, etc..).

This is a lot of new entry points to finally just have indirections in the mapping which makes it hard to understand IMHO whereas a (de)serializer is quite trivial to implement where API is broken and enable to do the version migration on the fly if desired even in complex object graphs.

Wdyt? Did you try that option?

**Comment by JohT** [comment]
I did a simple [jsonb-versioning-experiment](https://github.com/JohT/snippets/tree/master/jsonb-versioning-experiment). This is just one idea, maybe a base to discuss, not a solution.
- It keeps the object (Person, Name) free from interfaces and annotation, which leads to a bit too generic / type-unsafe-ish way to do it. 
- It pushes the responsibility to determine the version and to convert to the newest version to the value object.
- It contains per-object adapters (PersonAdapter, NameAdapter), as well as a full generic implementation (GenericVersionDeserializer).

**Comment by rmannibucau** [comment]
Did a post about versioning at https://rmannibucau.metawerx.net/post/jsonb-versinoing

It does not fully resolve the issue but shows that dome strategies work well without being technical so issue is maybe outside jsonb too.

**Comment by JohT** [comment]
I'll close this issue since there are ways to deal with versioning (see comments)
without the need for build in support (even if other serializers provide annotations for that).
