### ISSUE TITLE
provide @JsonbTransient on class level

### ISSUE THREAD

**Issue by nimo23** [eclipse-ee4j/jsonb-api#213]
Please provide `@JsonbTransient` on class level to list all properties which should be ignored for (de)serializing:

```
@JsonbTransient(value = {"id", "username", "getType", "setAge"})
public class User {

   private int id;
   private String username;
   private String type;
   private int age;

   public String getType(){
        return type;
    }

   public int setAge(){
        this.age = age;
   }

}
```

With this, the user can set and see all transient properties at a glance. And it avoids cluttering/polluting the class with a bunch of `@JsonbTransient` at each property/method.

Another solution could be:

```
// excludes properties/methods for json processing, others will be included
@JsonbExclude(value = {"id", "setAge"})

// inlcudes properties/methods for json processing, others will be excluded
@JsonbInclude(value = {"username", "getType"})

public class User {
    ..
}
```

**Comment by rmannibucau** [comment]
Hi @nimo23, you can do it with the visibility api. I think it matches more a custom need like that cause this looks less natural and highly error prone compared to putting jsonbtransient per field.

**Comment by nimo23** [comment]
>I think it matches more a custom need like that cause this looks less natural and highly error prone compared to putting jsonbtransient per field.

I dont think so. I described the benefits when putting it on class level. Btw, **Jackson** already has an annotation like that:
```

// jackson annotation
@JsonIgnoreProperties({ "id" })
public class User {

}
```

Highly error prone? Why? Then something like this should also be considered highly error prone:

```
@JsonbPropertyOrder(value = {
		"idUser",
		"username"})
public class User {
..
}
```

**Comment by rmannibucau** [comment]
Ok, here are the points to take in consideration IMHO:

1. Does it enable any new use case? No, we already handle it and it does not decouple the code from the config so it is purely syntaxic sugar and duplicates existing api.
2. Is it typesafe and model safe? No since it is based on strings, we will get the same ambiguity than the order annotation (are string json names or java field names) and the same user issues based on typo (the kind of issues you can spend a long time for nothing). Using an index in jsonbpriority would have been saner but not much inheritance friendly - whereas transient being can be handled more easily with accessors since it owns a single data (its presence) and no attribute.
3. Can the user handle such api easily? Yes, a custom visibility strategy does the job in a few lines and even enables more advanced conventions and api (I am thinking to this custom annotation but also libraries custom api).
4. This is likely not the mainstream jackson api so not sure se should promote it as a standard.
5. Other jakarta specs dont have it - even jaxb - and there is no real issue with it since the years it is used.
6. It makes it irrelevant on fields until creating another annotation which is not that nice on api side IMHO.

Hope it explains more where I am coming from.

**Comment by nimo23** [comment]
>1. Does it enable any new use case?

No. But it with this, the user can set and see all transient properties at a glance. And it avoids cluttering/polluting the class with a bunch of @JsonbTransient at each property/method.

>2. Is it typesafe and model safe?

Unfortunately, not.


>3. Yes, a custom visibility strategy does the job in a few lines and even enables more advanced conventions and api 

Do you mean `PropertyVisibilityStrategy` where we can only set `isVisible` for all fields or all methods? 


>4. This is likely not the mainstream jackson api 

It is a legal jackson annotation with reasonable use cases. If not, it would not exist. I dont know what you mean with mainstream.

>5.  Other jakarta specs dont have it 

I am only talking about json-b spec. Only because it does not exit in json-b yet, does not mean that users dislike it.

>6. It makes it irrelevant on fields until creating another annotation which is not that nice on api side IMHO.

I dont know what you mean.

**Comment by rmannibucau** [comment]
1. I guess it is a choice between 2 code style and it had been done in 1.0
2. I explained why the exception of order api
3.  Yes, default impl being trivial
4.i meant "used often enough", in dozens of apps using jackson I see at works none use that and with another dozen using jsonb there is no lack of that (ie using transient at field or method level is satisfying and simple with a unique codestyle which is a big plus)
5. Point is that this need would have popped in other spec if more than a codestyle and fact is it didnt so no reason jsonb becomes an exception IMHO
6. @JsonbTransient({}) or @JsonbTransient({"foo"}) String bar; would become an error at field level so api is no more natural IMO so we loose more than we gain as overall result if you cumulate all points.

**Comment by aguibert** [comment]
I agree with @rmannibucau here -- I don't like how the `@JsonbPropertyOrder` refers to properties as strings because it is very error prone and I don't think we should spread this sort of pattern further in the spec unless it unlocks a compelling use case that was not possible before. We often have users get confused about this, mainly because:
- If you type the string wrong in the `@JsonbPropertyOrder` annotation, it is silently ignored. This means as Java fields/methods get renamed or refactored it could change the behavior of `@JsonbPropertyOrder` because there is no type-safety guarantee like when the annotation is on the java element
- If you want to apply an ordering to a field/method that is renamed (e.g. `@JsonbProperty("foo") public String bar;`) it's not obvious without carefully reading the spec what string to put in `@JsonbPropertyOrder` annotation (`"foo"` or `"bar"`)

Regarding this point:
> And it avoids cluttering/polluting the class with a bunch of @JsonbTransient at each property/method.

We have an issue open for doing all JSON-B customizations programatically without modifying the source class at all here: https://github.com/eclipse-ee4j/jsonb-api/issues/88
I think this issue would solve the concern of "not cluttering the class with JSON-B annotations" while also unlocking a new use case of being able to apply JSON-B annotations for 3rd-party classes that the user cannot change.

**Comment by nimo23** [comment]
@aguibert Yes, you are right. Now I understand. Thanks for explanation. 

>I think this issue would solve the concern of "not cluttering the class with JSON-B annotations"

Yes, https://github.com/eclipse-ee4j/jsonb-api/issues/88 sounds very interesting!  Does this really mean that **I do not have to use json-b annotations** on classes to customize the json processing for each field/method? 

Actually I have a big problem using `json-b` in quarkus. The problem is described in https://github.com/quarkusio/quarkus/issues/5969. **And maybe https://github.com/eclipse-ee4j/jsonb-api/issues/88 would be a solution:** My main app uses jsonb-processing with jsonb annotated classes. The problem is that I also use a **3rd party dependency** which internally uses Jackson for json-processings. One one the 3rd party classes uses the following class to serialize with jackson:

```
@JsonPropertyOrder({"id", "name", "date", "enabled"})
public class Task implements Serializable {

    private static final long serialVersionUID = -3670232159675112851L;

    private final String id;
    private final String name;
    private final LocalDate date;
    private final Boolean enabled;
    
    // no-arg constructor for json-b is missing,
    // but jackson does not need a no arg constructor when class uses @JsonCreator
    @JsonCreator
    public Task(
            @JsonProperty("id") final String id,
            @JsonProperty("name") final String name,
            @JsonProperty("date") final LocalDate date,
            @JsonProperty("enabled") final Boolean enabled) {
        this.id = id;
        this.name = name;
        this.date = date;
        this.enabled = enabled;
    }

    public String getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public LocalDate getDate() {
        return date;
    }

    public Boolean getEnabled() {
        return isEnabled;
    }
}
```

however, when this class is executed, unfortunately, **json-b** tries to serialize the class of the 3rd party dependency **even though** the 3rd party dependency should use its jackson for json-b processing. This results in an error for json-b because json-b needs a default constructor which is missing:

```
No default constructor found.
	at org.eclipse.yasson.internal.serializer.ObjectDeserializer.getInstance(ObjectDeserializer.java:95)
	at org.eclipse.yasson.internal.serializer.AbstractContainerDeserializer.deserialize(Abstr
```

However, if json-b would ignore this class and delegate this json-processing to jackson (for what it was ment), then no error would occur, because jackson uses its `@JsonCreator`. Actually, I cannot find a solution to make such a scenario to work. So my question is: Can I disable the annotation processing or json processing with json-b for some classes with https://github.com/eclipse-ee4j/jsonb-api/issues/88? I dont know why json-b tries to serialize this class because this class was ment for jackson-processing and not for json-b-processing. Is there any config to use in json-b which would solve this issue? Or is https://github.com/eclipse-ee4j/jsonb-api/issues/88 the solution (e.g. programmatically disable the json-b-processing for some classes)?
