### ISSUE TITLE
Support a global PropertyOrderStrategy.NATURAL option

### ISSUE THREAD

**Issue by marceloverdijk** [eclipse-ee4j/jsonb-api#236]
Currently Jsonb supports the following ordering strategies:

- **`ANY`** : Using this strategy, the order of properties is not guaranteed to retain any order.
- **`LEXICOGRAPHICAL`** : Using this strategy, the order of properties is lexicographical.
- **`REVERSE`** : Using this strategy, the order of properties is in reverse order to lexicographical order.

I suggest to introduce a **`NATURAL`** option which maintains the order of the properties as defined in the class.

Currently we have to use `@JsonbPropertyOrder({ "id", "code", "name" })` on all classes to make this work.

**Comment by rmannibucau** [comment]
Hi @marceloverdijk , my 2cts would be that it should be possible to pass an implementation in JsonbConfig of a `Comparator<String>`, there are tons of potentially desired sortings (I'm thinking to pushing `x-*` to the end, ensuring `id` is first whatever other fields are, sorting by class hierarchy to cite only a few common ones). If we get that, natural support would become something like:

    new JsonbConfig().withPropertyOrderStrategy(Comparator.naturalOrder());

wdyt?

**Comment by marceloverdijk** [comment]
But would `naturalOrder()` not sort them alphabetically?

Maybe `NATURAL` as I suggested is not a good name then.

E.g. having a class like:

```
public class Continent {

    private String id;
    private String code;
    private String name;
}
```

I want the JSON output to maintain that order (`id`, `code`, `name`).

I mean this:

```
List<String> values = Arrays.asList("id", "code", "name");
values.sort(Comparator.naturalOrder());
System.out.println(values); 
```

will still print (alphabetically):

```
[code, id, name]
```

**Comment by rmannibucau** [comment]
@marceloverdijk right but it is the natural order for properties. point was more to move to an extension point than a ridig/fixed enum (which is not an enum ;)).

More specifically on the issue:

> order of the properties as defined in the class

Is only possible using an annotation processor since java 7 an it likely does not belong to JSON-B for multiple reasons (avoiding build setup, integration with the ecosystem, JakartaEE consistency, ...). So long story short, if you have an extension point as mentionned, you can generate with an annotation processor a descriptor storing the field order (can be a properties, should be sufficient) and you plug a comparator handling that. Probably saner alternative for you using this extension point is to add a custom `@Order(value)` on fields and sort using that annotation the fields.

So overall, at spec level, it requires to get the class name so maybe `Function<Class<?>, Comparator<String>>` with a shortcut on `Comparator<String>` if all classes share the same impl.

Hope it makes sense.

**Comment by marceloverdijk** [comment]
Yes, I already thought this request was a long shot ;-)

I'm currently using a `@JsonbPropertyOrder({ "id", "code, "name" })` on my class, but this needs to be done on every class (no global option). And it might be error prone as it is easy to forget to add when a new field is added to the class,

**Comment by rmannibucau** [comment]
@marceloverdijk guess the best you can do *today* to avoid errors is to write a custom annotation processor adding/replacing `@JsonbPropertyOrder` at compile time. No more error, matches your original request and no need to wait for any new spec change. You still have to handle some weird cases if you want to be generic (like what about shadowed attributes in inheritances and things like that) but sounds very doable.

**Comment by aguibert** [comment]
I'm going to close this issue though. I think what @rmannibucau suggested could be useful, but I haven't seen any users ask for it so I'd prefer to not provide it until somebody asks for it.

Thanks for taking the time to write up this enhancement proposal though @marceloverdijk!

**Comment by rmannibucau** [comment]
@aguibert a side note maybe, in Johnzon you can set a comparator (not a fn yet) since v1 so it can also be why we don't get much reports about this need.
